### ISSUE TITLE
M-Pathways/API Directory endpoint has some limit

### ISSUE THREAD

**Issue by ssciolla** [tl-its-umich-edu/placement-exams#15]
During testing, I discovered that the M-Pathways API Directory endpoint seems to have some sort of limit, probably based on the character length of the JSON body or headers. The cutoff seems to occur when sending somewhere between 150 and 213 scores. When too many scores are sent, a `500` status code is received, along with the following text body:

```
{ "httpCode":"500", "httpMessage":"Internal Server Error", "moreInformation":"Failed to process response headers" }
```

While it will be unlikely that a single exam will have this many records to send at once, we should handle this edge case by chunking the `Submission` instances to send. Using a utility function like the following in `ScoresOrchestration.main()` should do the trick.

```
def chunk_list(input_list: List[Any], chunk_size: int = 100):
    """Chunks a given list into a list of lists of a specified size."""
    chunks = [input_list[x:x + chunk_size] for x in range(0, len(input_list), chunk_size)]
    LOGGER.debug(chunks)
    return chunks
```

**Comment by ssciolla** [comment]
We have used `chunk_list` in production, but not with more than 100 submissions.

To QA, I suggest completing the following steps on your machine:

- [ ] Delete `.data`.
- [ ] Make sure you have Spanish Placement in your fixtures, and modify the `default_time_filter` to be the beginning of 2020.
- [ ] Run the application (it may take a few minutes), and observe the log to ensure the chunking is working properly.

**Comment by zqian** [comment]
Tested locally. Got 537 submission since July 1, 2020, and got five different transmitted_timestamp values. It is working as expected.
