### ISSUE TITLE
Add docker-compose for setting up local MySQL database

### ISSUE THREAD

**Issue by ssciolla** [tl-its-umich-edu/placement-exams#2]
To assist with #1, it will make sense to add a `docker-compose` file that will automatically set up a MySQL service for testing purposes. The `docker-compose` files from `course-inventory` or `student_explorer` can serve as models.

**Comment by ssciolla** [comment]
@zqian , can you just confirm `docker-compose` has worked for you and move to "Done"?

**Comment by zqian** [comment]
I have used the docker-compose MySQL all along.
