### ISSUE TITLE
Discard submission dictionaries from Canvas with no score

### ISSUE THREAD

**Issue by ssciolla** [tl-its-umich-edu/placement-exams#26]
During testing, we seem to have discovered that it is pretty easy to create a submission with a null score when entering scores manually. This may happen if a user starts to enter a score and then deletes it. It seems like it would be simple enough to check whether the submission has a non-`null` value for the score before adding it to the database. The `graded_at` value should be updated when a new score is entered, so the most up-to-date submission should still be processed correctly.

**Comment by ssciolla** [comment]
To QA, I suggest the following:

- [ ] Review the code.
- [ ] Go to one of the French exams on Canvas test.
- [ ] Remove an existing score from the aggregate score column.
- [ ] Run the job in Test Jenkins, observe the log to see discarded message.
- [ ] Add back the score that you removed.
- [ ] Run the job in Test Jenkins again, observe the successful score being submitted.

**Comment by pushyamig** [comment]
Test passes
