### ISSUE TITLE
Make max_request_attempts configurable for `get_sub_dicts_for_exam`

### ISSUE THREAD

**Issue by ssciolla** [tl-its-umich-edu/placement-exams#32]
While `api_call_with_retries` allows for a `max_req_attempts` parameter, right now we are only using the default of `3` in `ScoresOrchestration.get_sub_dicts_for_exam`. Really this should be configurable in case we encounter repeated errors when using the Canvas API that we want to work through. This issue is low priority, as what we have works.

**Comment by ssciolla** [comment]
@zqian, could you QA this on your local machine when you have a moment? Here is how I tested it:

1) Update your `.env` to include the `MAX_REQ_ATTEMPTS` variable with some value other than "3".
2) Update your `fixtures.json` file so at least one exam uses the wrong assignment ID (one that doesn't exist in that course, `999999` worked for me).
3) Run the job, and note that the exam with the wrong assignment ID fails X times before bailing out, where X is the number you specified in `MAX_REQ_ATTEMPTS`.

Let me know if you have any questions.

**Comment by zqian** [comment]
I have followed the above instructions:

1. set MAX_REQ_ATTEMPTS=7 in ~/secrets/placement-exams/.env file 
2. setup  "assignment_id": 999999 for pe.exam
3. docker-compose up
4. verified there are 7 attempts logged in the output text, all failed with WARNING - {"error":"invalid assignment ids requested"}
