### ISSUE TITLE
Strip whitespace from Canvas login_id values

### ISSUE THREAD

**Issue by ssciolla** [tl-its-umich-edu/placement-exams#36]
I noticed while doing research on special characters that whitespace is sometimes included at the end of Canvas `login_id` values (which are cross-walked to `Submission.student_uniqname`). Specifically, I saw this occurring with friend accounts. While this is an edge case, it seems like it could lead to a strange situation where we send across a score to M-Pathways, but don't get the same uniqname back; the M-Pathways (or API Directory) code seems to remove leading and trailing whitespace. That would mean the application would interpret the score as not being transmitted, even though it was. Seems like the simplest solution would be to just strip whitespace before entering the data in the database. A `canvas_subs` fixture and some kind of`ScoresOrchestration` test case probably make sense.

**Comment by ssciolla** [comment]
I don't know the best way to QA this issue, since I haven't actually seen this happen before. However, I know these leading and trailing values are possible (though very unlikely) because of my analysis of the field in the data warehouse. I also witnessed the stripping behavior on the M-Pathways side during testing. I guess I would do the following:

- [ ] Understand the problem.
- [ ] Look at the data in the data warehouse using a query like this:
   ```
   SELECT pd.id, pd.canvas_id, pd.unique_name, pd.sis_user_id
   FROM pseudonym_dim pd
   WHERE pd.unique_name ~ '[[:space:]]';
   ```
- [ ] Review my code.
- [ ] Run my tests.

**Comment by pushyamig** [comment]
Test Passing
