### ISSUE TITLE
Modify application to use utf8mb4

### ISSUE THREAD

**Issue by ssciolla** [tl-its-umich-edu/placement-exams#37]
After doing some testing, I determined that the database and process can handle most Unicode characters, but the database appears to struggle with the four-byte UTF8 characters. Colleagues have been working on handling this in other applications (see https://github.com/tl-its-umich-edu/my-learning-analytics/pull/992), and `django_mysql` describes the issue and how to handle it here: https://django-mysql.readthedocs.io/en/latest/checks.html#django-mysql-w003-utf8mb4

It seems like, if this doesn't cause other issues, it would be worth resolving now.

_Originally posted by @ssciolla in https://github.com/tl-its-umich-edu/placement-exams/issues/13#issuecomment-668829802_

**Comment by ssciolla** [comment]
Because this is a new application, I think we can get away with just changing `settings.py` and the initialization in `docker-compose` for `mysql`; a migration would really only be necessary if we needed to update an existing database.

**Comment by ssciolla** [comment]
To QA, I suggest the following:

- [ ] Review the changes.
- [ ] Run the application at least once and the test suite using a new database (i.e. deleting `.data`).
- [ ] Try modifying one of the test fixtures in OpenShift to include an emoji in a `VARCHAR` field.

**Comment by pushyamig** [comment]
I verified that database tables are all utf8mb4 locally as well as Dev. I suppose since Prod DB tables are not step up I am assuming similar protocol follwed
