### ISSUE TITLE
Upgrade to Django 3.2

### ISSUE THREAD

**Issue by ssciolla** [tl-its-umich-edu/placement-exams#65]
Since there have been a few 3.2 Django releases (`3.2.4` is the latest), we can upgrade to 3.2 instead of continuing to update for `3.1.x` patch releases.

This should also make unnecessary the `dependabot` PR incorporating the `3.1.x` security patches.

**Comment by zqian** [comment]
The script ran successfully on both localhost and test-jenkins server.
