### ISSUE TITLE
Perform dependency update

### ISSUE THREAD

**Issue by ssciolla** [tl-its-umich-edu/placement-exams#70]
We're overdue for a dependency update, and the last one I did was never released. I'd like to take care of this. We should also look into moving to Python 3.9; I think the main feature we may want to pick up is the use of `list` and `dict` for typing (https://docs.python.org/3/whatsnew/3.9.html).

**Comment by ssciolla** [comment]
I'm reopening this since my last update was dormant enough that it's time to look at Python 3.10 and pick up Python package updates again.

**Comment by zqian** [comment]
script ran successfully with python upgrade on both localhost and test-jenkins server.
